import type { Settings } from "./types";

/**
 * Global settings — the single edit point for the agency's real data.
 * Address and phone are the verified public details of ISLEM Immobilier.
 * Everything else (email, social links, hours) must be confirmed by the
 * agency before launch; defaults are clearly structured to replace.
 */
export const settings: Settings = {
  brand: {
    name: "ISLEM Immobilier",
    legalName: "ISLEM Immobilier — Agence immobilière, Alger Centre",
    tagline: {
      fr: "Agence immobilière à Alger Centre",
      ar: "وكالة عقارية في وسط مدينة الجزائر",
    },
  },
  contact: {
    phoneE164: "+213772226303",
    phoneDisplay: "+213 772 226 303",
    whatsappPhone: "213772226303",
    email: "contact@islemimmobilier.dz",
    address: {
      fr: "30 Rue Didouche Mourad, Alger Centre, Algérie",
      ar: "30 شارع ديدوش مراد، الجزائر الوسطى، الجزائر",
    },
    mapCoords: { lat: 36.7762, lng: 3.0616 },
    hours: {
      fr: [
        { days: "Dimanche – Jeudi", hours: "09:00 – 17:30" },
        { days: "Samedi", hours: "09:00 – 13:00" },
        { days: "Vendredi", hours: "Fermé" },
      ],
      ar: [
        { days: "الأحد – الخميس", hours: "09:00 – 17:30" },
        { days: "السبت", hours: "09:00 – 13:00" },
        { days: "الجمعة", hours: "مغلق" },
      ],
    },
  },
  social: {
    facebook: undefined,
    instagram: undefined,
    linkedin: undefined,
    googleBusiness: undefined,
  },
  seo: {
    siteName: "ISLEM Immobilier",
    titleTemplate: "%s — ISLEM Immobilier",
    defaultDescription: {
      fr: "ISLEM Immobilier, agence immobilière à Alger Centre : appartements, villas, terrains, locaux commerciaux et bureaux à la vente et à la location. Sélection rigoureuse, accompagnement professionnel de A à Z.",
      ar: "ISLEM Immobilier، وكالة عقارية في وسط مدينة الجزائر: شقق وفيلات وأراضٍ ومحلات تجارية ومكاتب للبيع والكراء. انتقاء دقيق للعقارات ومرافقة احترافية من الألف إلى الياء.",
    },
    keywords: [
      "immobilier Alger Centre",
      "agence immobilière Alger Centre",
      "appartement Alger",
      "villa Alger",
      "location appartement Alger",
      "vente appartement Alger",
      "immobilier Alger",
      "agence immobilière Algiers real estate",
    ],
    ogImage: "/fr/opengraph-image", // per-locale OG card generated by app/[locale]/opengraph-image.tsx
  },
  site: {
    url: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
    currency: "DZD",
    currencySymbol: { fr: "DA", ar: "دج" },
    priceSuffix: {
      fr: "par mois",
      ar: "شهريًا",
    },
  },
  content: {
    listingsDisclaimer: {
      fr: "Les informations de cette annonce sont fournies à titre indicatif et ne constituent pas un engagement contractuel. Les visuels sont des illustrations et seront remplacés par les photos officielles de chaque bien.",
      ar: "معلومات هذا الإعلان مُقدَّمة للتعريف فقط ولا تُشكّل التزامًا تعاقديًا. الصور المعروضة توضيحية وسيتم استبدالها بالصور الرسمية لكل عقار.",
    },
    privacyNote: {
      fr: "Vos coordonnées sont utilisées uniquement pour traiter votre demande et ne sont ni revendues ni partagées.",
      ar: "تُستعمل معلوماتكم فقط لدراسة طلبكم، ولا تُباع ولا تُشارك مع أي جهة.",
    },
  },
};

export function waLink(text?: string): string {
  const base = `https://wa.me/${settings.contact.whatsappPhone}`;
  return text ? `${base}?text=${encodeURIComponent(text)}` : base;
}

export function telLink(): string {
  return `tel:${settings.contact.phoneE164}`;
}
